### ISSUE TITLE
Further work

### ISSUE THREAD

**Issue by ghost** [leeola/go-react#1]
I am also very interested in exending this. Perhaps to include reflux aspects.

Did the code / architect ture not work out IR did you just loose interest ?
Just so I know the current state and if I should fork.

**Comment by leeola** [comment]
Hmm, i meant to update the README with my findings/givings-up _(on this specific method)_ - apparently i did not.

I had trouble dealing with managing the State _(as the lack of a State example eludes to)_. There was a lot of overhead at the Rendering stage, but that could be dealt with. The larger problem _(for me)_ was coming up with a pattern to deal with state transfer.

React's state objects are a pattern to guide developers on managing their application state. However, in Gopher, i did not want to use this same pattern explicitly. Boiling down 1:1 Gopher objects into React state felt needlessly expensive.

I ended up trying to change to a more low level library _(virtualdom)_, in hopes to remove the state issue _(since we can manage State just fine in Go, imo)_, and that was going decently - still though, design was difficult due to needing to needlessly bridge from Go to JavaScript at crucial points. In the case of VirtualDom, it was being notified of events for a given Element. Ie, if an element is being unmounted, you want to know so you can take deconstruction action. It ended up being clear that i would be far better off creating a raw GopherJS implementation of VirtualDom from the ground up. Though, that is not something i wanted to tackle currently.

In both cases it was mapping from design patterns from a pre-existing JS library, onto Golang, that was the hurdle for me. I found it much cleaner to map one way, ie `Go -> JS` as you can create whatever design patterns you want.

When i have the time, my next plan _(on this goal of getting GopherJS into browser heh)_, is to create a very limited parser for Go's HTML Templating lib and map those calls to [incremental dom](https://github.com/google/incremental-dom). Because this is such a low level solution to vdom, they have very little expectation over what your patterns should be _(as far as i understand)_. You just use their api, and spit out some DOM. Theoretically you could map Go templates to this, it would be entirely one way, and the above Go patterns/frameworks would be irrelevant.

With any luck, you could even create very Go-centric route handler patterns, and calls to Render the UI could feel very similar _(or even identical/isomorphic)_ to backend HTML Rendering.

But yea, that basically sums up my thoughts on React & VirtualDom with GopherJS. I think it's totally possible to use React, you'll just be fighting it at a few points. The further we get our Go code away from JS Library pattern requirements, the better - in my opinion :)

**Comment by ghost** [comment]
Thanks for that.

Pure golang to js via gopherjs sounds like a winner to me.
You can use it for complex stuff server side and client side.

Incremental dom. Do the same. Run on either server side or clientside with gopherjs.

Don't worry about the client side size. Any app needing this is big anyway.

So how to proceed ? Might be worth doing a start from scratch ?

**Comment by ghost** [comment]
Just to be clear that mean dropping react fully ? It just gets in the way. Curious what happens here ?

We can either try and shoe horn it so it maps to react expectations OR forget about react.

If we forget about react it might be best. I would try to map it into web components personally. Ie polymer. But not sure to be frank

**Comment by leeola** [comment]
Imo, forget about React. I mean, if you or anyone wants to try it, Go for it! I hope you succeed! Personally i am dropping it entirely though.

GopherJS has enough performance concerns _(the bloat from channels alone scares me quite a bit)_, so mapping i think is just a lost cause any way you slice it. I would love to be wrong though :)

But yea, i think going one direction is as optimal as you can get. Any framework that fits that, should _(in theory)_ be fine. Whether that is `Go -> Polymer`, or `Go -> Incremental Dom` or even `Go -> DOM API`, it shoud _(in theory)_ all be roughly the same. It's the bidirection that is troublesome, _in my experience_.

Personally i don't have time to work on this space for quite some time, so don't wait for me on anything. Best of luck :)

**Comment by ghost** [comment]
I agree.
I have some time. I will explore a bit for now.
Closing and cheers
